version: '3.8'

services:
  warframe-checklist:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: warframe-task-checklist
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - TZ=${TIMEZONE:-UTC}